DELIMITER $$

DROP PROCEDURE IF EXISTS OUTPUT_WITH_RS$$
CREATE PROCEDURE OUTPUT_WITH_RS(
OUT s1 VARCHAR(50),
OUT s2 VARCHAR(50),
OUT l1 BIGINT,
OUT status SMALLINT,
OUT msg VARCHAR(50)
)
BEGIN
	SET s1 = 'HELLO';
	SET s2 = 'WORLD';
	SET l1 = 99;
	
	select ROUTINE_NAME, CREATED from information_schema.ROUTINES;
END$$

DELIMITER ;

