-- SQL SERVER 


USE [TEST]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = 'EXE_NO_IN_NO_OUT') DROP PROC EXE_NO_IN_NO_OUT
GO

CREATE PROCEDURE [dbo].[EXE_NO_IN_NO_OUT]
  @SUCCESS SMALLINT OUTPUT, 
  @MESSAGE varchar(50) OUTPUT
AS

SELECT GETDATE()

SET @SUCCESS = 0-- success
SET @MESSAGE = ''

GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = 'ECHO') DROP PROC ECHO
GO

CREATE PROCEDURE [dbo].[ECHO]
  @SOME_INPUT   VARCHAR(50),
  @SUCCESS SMALLINT OUTPUT, 
  @MESSAGE varchar(50) OUTPUT
AS

SELECT GETDATE()

SET @SUCCESS = 0-- success
SET @MESSAGE = @SOME_INPUT

GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = 'OUTPUT') DROP PROC OUTPUT
GO

CREATE PROCEDURE [dbo].[OUTPUT]
  @SOME_OUPUT1   VARCHAR(50) OUTPUT,
  @SOME_OUPUT2   VARCHAR(50) OUTPUT,
  @SOME_OUPUT3   BIGINT OUTPUT,
  @SUCCESS SMALLINT OUTPUT, 
  @MESSAGE varchar(50) OUTPUT
AS

SET @SOME_OUPUT1 = 'HELLO'
SET @SOME_OUPUT2 = 'WORLD'
SET @SOME_OUPUT3 = 99

SET @SUCCESS = 0-- success

GO




IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = 'OUTPUT_WITH_RS') DROP PROC OUTPUT_WITH_RS
GO

CREATE PROCEDURE [dbo].[OUTPUT_WITH_RS]
  @SOME_OUPUT1   VARCHAR(50) OUTPUT,
  @SOME_OUPUT2   VARCHAR(50) OUTPUT,
  @SOME_OUPUT3   BIGINT OUTPUT,
  @SUCCESS SMALLINT OUTPUT, 
  @MESSAGE varchar(50) OUTPUT
AS

SELECT ROUTINE_NAME, CREATED FROM INFORMATION_SCHEMA.ROUTINES

SET @SOME_OUPUT1 = 'HELLO'
SET @SOME_OUPUT2 = 'WORLD'
SET @SOME_OUPUT3 = 99

SET @SUCCESS = 0-- success

GO



IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = 'SP_WITH_INT_OUTPUT') DROP PROC SP_WITH_INT_OUTPUT
GO

CREATE PROCEDURE [dbo].[SP_WITH_INT_OUTPUT]
  @SUCCESS SMALLINT OUTPUT, 
  @MESSAGE varchar(50) OUTPUT
AS

SELECT GETDATE()

SET @SUCCESS = 1  -- fail
SET @MESSAGE = ''

GO